title: Introduction to Deep Learning Workshop
logo: /assets/img/logo.gif
description: Monday, August 7 & Tuesday, August 8, 2023 | 8:00 AM - 11:00 AM PDT

show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
